// Constants for button and panel elements
const buttons = document.querySelectorAll('.button');
const middlePanel = document.querySelector('.middle-panel');
const sliders = document.querySelector('.sliders');
const generatedCode = document.getElementById('generated-code');
const generateCodeButton = document.getElementById('generate-code');
const errorMessage = document.getElementById('error-message');

// Function to handle button click events
function handleButtonClick(event) {
    const section = event.target.getAttribute('data-section');
    
    // Clear previous selections and styles
    buttons.forEach((btn) => btn.classList.remove('active'));
    middlePanel.innerHTML = '';
    
    // Update the selected button and apply active style
    event.target.classList.add('active');
    
    // Add content to the middle panel based on the selected button
    switch (section) {
        case 'HEAD':
            // Add HEAD content to the middle panel
            // You can create and append elements for the cube and sliders here
            break;
        case 'FACE':
            // Add FACE content
            break;
        case 'BODY':
            // Add BODY content
            break;
        // Add cases for other sections (HAND/LEGS, FEET/HANDS, CLOTHES) here
    }
}

// Function to generate code
function generateCode() {
    const selectedAI = document.getElementById('ai-select').value;
    const selectedRig = document.getElementById('rig-select').value;
    const selectedOutput = document.getElementById('output-select').value;

    if (!selectedAI || !selectedRig || !selectedOutput) {
        // Show an error message and return if any selection is missing
        errorMessage.style.display = 'block';
        generatedCode.innerHTML = '';
        return;
    }
    
    // Generate code based on selections and display it
    const code = `
        // Code generated by Emersa Studio
        AI: ${selectedAI}
        Rig: ${selectedRig}
        Output: ${selectedOutput}
        // Add more code generation logic here
    `;
    
    generatedCode.innerText = code;
    errorMessage.style.display = 'none';
}

// Add event listeners for button clicks
buttons.forEach((button) => {
    button.addEventListener('click', handleButtonClick);
});

// Add event listener for generate code button
generateCodeButton.addEventListener('click', generateCode);
