// DOM Elements
const buttons = document.querySelectorAll('.button');
const middlePanel = document.querySelector('.middle-panel');
const slidersContainer = document.querySelector('.sliders');
const aiSelect = document.getElementById('ai-select');
const rigSelect = document.getElementById('rig-select');
const outputSelect = document.getElementById('output-select');
const generateButton = document.getElementById('generate-button');
const errorMessage = document.getElementById('error-message');
const generatedCode = document.getElementById('generated-code');
const rightPanel = document.querySelector('.right-panel');

// Data
const sections = {
  HEAD: 'Head Content',
  FACE: 'Face Content',
  BODY: 'Body Content',
  'HAND/LEGS': 'Hand/Legs Content',
  'FEET/HANDS': 'Feet/Hands Content',
  CLOTHES: 'Clothes Content',
};

const rigOptions = ['Rig Option 1', 'Rig Option 2', 'Rig Option 3'];
const outputOptions = ['Output Option 1', 'Output Option 2', 'Output Option 3'];

// Event Listeners
buttons.forEach((button) => {
  button.addEventListener('click', () => handleButtonClick(button.dataset.section));
});

generateButton.addEventListener('click', generateCode);

// Functions
function handleButtonClick(section) {
  // Clear previous selections and content
  middlePanel.innerHTML = '';
  slidersContainer.innerHTML = '';

  // Create and display content based on the selected section
  const sectionContent = sections[section];
  middlePanel.innerHTML = sectionContent;

  // Move the buttons above the sliders
  buttons.forEach((button) => {
    button.style.transform = 'translateY(0)';
  });

  // Create sliders based on the selected section
  for (let i = 1; i <= 9; i++) {
    const slider = document.createElement('input');
    slider.type = 'range';
    slider.min = '0';
    slider.max = '100';
    slider.value = '50';
    slidersContainer.appendChild(slider);
  }
}

function generateCode() {
  const selectedAI = aiSelect.value;
  const selectedRig = rigSelect.value;
  const selectedOutput = outputSelect.value;

  if (!selectedAI || !selectedRig || !selectedOutput) {
    // Show an error message and return if any selection is missing
    errorMessage.style.display = 'block';
    generatedCode.innerHTML = '';
    return;
  }

  // Generate code based on selections
  const code = `
    // Code generated by Emersa Studio
    AI: ${selectedAI}
    Rig: ${selectedRig}
    Output: ${selectedOutput}
    // Add more code generation logic here
  `;

  generatedCode.innerText = code;
  errorMessage.style.display = 'none';
}

// Initialize rig and output selects
rigOptions.forEach((option) => {
  const rigOption = document.createElement('option');
  rigOption.value = option;
  rigOption.textContent = option;
  rigSelect.appendChild(rigOption);
});

outputOptions.forEach((option) => {
  const outputOption = document.createElement('option');
  outputOption.value = option;
  outputOption.textContent = option;
  outputSelect.appendChild(outputOption);
});

// Default section selection
handleButtonClick('HEAD');
